# Generated by Django 4.2.1 on 2023-06-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_userprofile_alter_task_user_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="telegram_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
