# Generated by Django 4.2.1 on 2023-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_userprofile_telegram_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
