# Generated by Django 4.2.1 on 2023-06-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_task_task_info_task_telegram_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="task_info",
        ),
        migrations.RemoveField(
            model_name="task",
            name="telegram_id",
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
